from __future__ import annotations

"""Phase A: RAGAS production evaluation on 50 questions / 3 distributions."""

import json
import os
import sys
from dataclasses import dataclass
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from config import ANSWERS_PATH, TEST_SET_PATH

Distribution = str
METRICS = ("faithfulness", "answer_relevancy", "context_precision", "context_recall")
DISTRIBUTIONS = ("factual", "multi_hop", "adversarial")

DIAGNOSTIC_TREE = {
    "faithfulness": (
        "The generated answer is not sufficiently grounded in retrieved evidence.",
        "Use stricter context-only generation, remove noisy chunks, and keep temperature low.",
    ),
    "answer_relevancy": (
        "The answer does not directly satisfy the question.",
        "Preserve intent/entities/units and make the generation prompt more direct.",
    ),
    "context_precision": (
        "The retrieved context contains too much irrelevant evidence.",
        "Improve reranking/metadata filtering or reduce final top-k.",
    ),
    "context_recall": (
        "The retrieved context is missing required evidence.",
        "Improve chunking, hybrid recall, query decomposition, or parent retrieval.",
    ),
}


@dataclass
class RagasResult:
    question_id: int
    distribution: Distribution
    question: str
    answer: str
    contexts: list[str]
    ground_truth: str
    faithfulness: float
    answer_relevancy: float
    context_precision: float
    context_recall: float

    @property
    def avg_score(self) -> float:
        return sum(getattr(self, metric) for metric in METRICS) / len(METRICS)

    @property
    def worst_metric(self) -> str:
        return min(METRICS, key=lambda metric: getattr(self, metric))


def _score(value: Any) -> float:
    try:
        score = float(value)
    except (TypeError, ValueError):
        return 0.0
    if score != score:  # NaN
        return 0.0
    return max(0.0, min(1.0, score))


def _field(row: Any, name: str) -> Any:
    if isinstance(row, dict):
        return row.get(name)
    return getattr(row, name, None)


def load_test_set_50q(path: str = TEST_SET_PATH) -> list[dict]:
    """Load and validate the Day 24 50-question test set."""
    with open(path, encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, list):
        raise ValueError("test_set_50q.json must contain a list")
    return data


def load_answers(path: str = ANSWERS_PATH) -> list[dict]:
    """Load answers generated by ``setup_answers.py``."""
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"answers_50q.json not found at {path}. Run: python setup_answers.py"
        )
    with open(path, encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, list):
        raise ValueError("answers_50q.json must contain a list")
    return data


def group_by_distribution(test_set: list[dict]) -> dict[str, list[dict]]:
    """Task 1: group questions into factual / multi_hop / adversarial buckets."""
    groups: dict[str, list[dict]] = {distribution: [] for distribution in DISTRIBUTIONS}
    for item in test_set:
        distribution = item.get("distribution")
        if distribution not in groups:
            raise ValueError(f"Unknown distribution: {distribution!r}")
        groups[distribution].append(item)
    return groups


def run_ragas_50q(answers: list[dict]) -> list[RagasResult]:
    """Task 2: run the student's Day 18 ``evaluate_ragas`` on all Day 24 answers."""
    if not answers:
        return []

    from src.m4_eval import evaluate_ragas

    questions = [str(item["question"]) for item in answers]
    answer_texts = [str(item["answer"]) for item in answers]
    contexts = [[str(ctx) for ctx in item.get("contexts", [])] for item in answers]
    ground_truths = [str(item["ground_truth"]) for item in answers]

    raw = evaluate_ragas(questions, answer_texts, contexts, ground_truths)
    per_question = raw.get("per_question", []) if isinstance(raw, dict) else []
    if len(per_question) != len(answers):
        raise RuntimeError(
            "Day 18 evaluate_ragas() returned an unexpected per_question length: "
            f"{len(per_question)} for {len(answers)} answers"
        )

    results: list[RagasResult] = []
    for item, row in zip(answers, per_question):
        results.append(
            RagasResult(
                question_id=int(item["id"]),
                distribution=str(item["distribution"]),
                question=str(item["question"]),
                answer=str(item["answer"]),
                contexts=[str(ctx) for ctx in item.get("contexts", [])],
                ground_truth=str(item["ground_truth"]),
                faithfulness=_score(_field(row, "faithfulness")),
                answer_relevancy=_score(_field(row, "answer_relevancy")),
                context_precision=_score(_field(row, "context_precision")),
                context_recall=_score(_field(row, "context_recall")),
            )
        )
    return results


def bottom_10(results: list[RagasResult]) -> list[dict]:
    """Task 3: return the ten lowest average-score questions with diagnostics."""
    output: list[dict] = []
    for rank, result in enumerate(sorted(results, key=lambda row: row.avg_score)[:10], start=1):
        diagnosis, fix = DIAGNOSTIC_TREE[result.worst_metric]
        output.append(
            {
                "rank": rank,
                "question_id": result.question_id,
                "distribution": result.distribution,
                "question": result.question,
                "avg_score": round(result.avg_score, 4),
                "worst_metric": result.worst_metric,
                "diagnosis": diagnosis,
                "suggested_fix": fix,
            }
        )
    return output


def cluster_analysis(results: list[RagasResult]) -> dict:
    """Task 4: build worst-metric × distribution failure matrix and an insight."""
    matrix = {
        metric: {distribution: 0 for distribution in DISTRIBUTIONS}
        for metric in METRICS
    }
    for result in results:
        if result.distribution not in DISTRIBUTIONS:
            continue
        matrix[result.worst_metric][result.distribution] += 1

    if not results:
        return {
            "matrix": matrix,
            "dominant_failure_distribution": None,
            "dominant_failure_metric": None,
            "insight": "No evaluation results were available for failure clustering.",
        }

    dominant_distribution = max(
        DISTRIBUTIONS,
        key=lambda distribution: sum(matrix[m][distribution] for m in METRICS),
    )
    dominant_metric = max(METRICS, key=lambda metric: sum(matrix[metric].values()))
    _, suggested_fix = DIAGNOSTIC_TREE[dominant_metric]
    insight = (
        f"'{dominant_distribution}' contains the largest failure cluster and "
        f"'{dominant_metric}' is the most frequent weakest metric. "
        f"Recommended next action: {suggested_fix}"
    )
    return {
        "matrix": matrix,
        "dominant_failure_distribution": dominant_distribution,
        "dominant_failure_metric": dominant_metric,
        "insight": insight,
    }


def save_phase_a_report(
    results: list[RagasResult],
    clusters: dict,
    path: str = "reports/ragas_50q.json",
    backend: str = "unknown",
    backend_error: str | None = None,
) -> None:
    """Save real Phase A results; the backend field prevents proxy scores being misreported."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    per_distribution: dict[str, dict] = {}
    for distribution in DISTRIBUTIONS:
        subset = [row for row in results if row.distribution == distribution]
        if not subset:
            continue
        per_distribution[distribution] = {
            "count": len(subset),
            **{
                metric: round(sum(getattr(row, metric) for row in subset) / len(subset), 6)
                for metric in METRICS
            },
            "avg_score": round(sum(row.avg_score for row in subset) / len(subset), 6),
        }

    report = {
        "backend": backend,
        "backend_error": backend_error,
        "total_questions": len(results),
        "per_distribution": per_distribution,
        "failure_clusters": clusters,
        "bottom_10": bottom_10(results),
    }
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(report, handle, ensure_ascii=False, indent=2)
    print(f"Phase A report saved -> {path} (backend={backend})")


def main() -> None:
    test_set = load_test_set_50q()
    groups = group_by_distribution(test_set)
    print(f"Loaded {len(test_set)} questions")
    for distribution, items in groups.items():
        print(f"  {distribution}: {len(items)}")

    answers = load_answers()
    if len(answers) != len(test_set):
        raise RuntimeError(f"Expected {len(test_set)} answers, found {len(answers)}")

    # Call once here so we can capture the Day 18 backend in addition to normalized rows.
    from src.m4_eval import evaluate_ragas

    raw = evaluate_ragas(
        [str(a["question"]) for a in answers],
        [str(a["answer"]) for a in answers],
        [[str(c) for c in a.get("contexts", [])] for a in answers],
        [str(a["ground_truth"]) for a in answers],
    )
    per_question = raw.get("per_question", [])
    if len(per_question) != len(answers):
        raise RuntimeError("Day 18 RAGAS result does not contain all 50 per-question rows")

    results: list[RagasResult] = []
    for item, row in zip(answers, per_question):
        results.append(
            RagasResult(
                question_id=int(item["id"]),
                distribution=str(item["distribution"]),
                question=str(item["question"]),
                answer=str(item["answer"]),
                contexts=[str(c) for c in item.get("contexts", [])],
                ground_truth=str(item["ground_truth"]),
                faithfulness=_score(_field(row, "faithfulness")),
                answer_relevancy=_score(_field(row, "answer_relevancy")),
                context_precision=_score(_field(row, "context_precision")),
                context_recall=_score(_field(row, "context_recall")),
            )
        )

    clusters = cluster_analysis(results)
    save_phase_a_report(
        results,
        clusters,
        backend=str(raw.get("backend", "unknown")),
        backend_error=str(raw.get("error")) if raw.get("error") else None,
    )
    print("Bottom 10:")
    for item in bottom_10(results):
        print(
            f"  #{item['rank']} Q{item['question_id']} [{item['distribution']}] "
            f"avg={item['avg_score']:.3f} worst={item['worst_metric']}"
        )


if __name__ == "__main__":
    main()
